# Copyright (c) 2021-2022 Simon. All rights reserved.

# SPDX-License-Identifier: MIT

include $(PRJ_ROOT_DIR)/scripts/fonts_color.mk

SHELL := /bin/bash
PWD := $(shell pwd)
DRV_DIR_SINGLE := $(shell basename $(PWD))

all:
	@ echo -e "$(YELLOW)$(BOLD)[5] INTO $(UNDERLINE)$(DRV_DIR_SINGLE)$(END) $(YELLOW)$(BOLD)COMPILE...$(END)"
